java_test(
  name = "AnsiColorParserTest",
  srcs = ["AnsiColorParserTest.java"],
  size = "small",
  deps = [
    "@maven//:com_google_guava_guava",
    "@maven//:com_google_truth_truth",
    "@maven//:junit_junit",
    "//java/com/jeffreys/junit",
    "//java/com/jeffreys/common/ansi",
  ],
)
